name: desafio_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: 3.4.1+1
  mobx: 2.0.4
  flutter_mobx: 2.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true